work_dir: ./work_dir/ntu/csub/ctrgcn

# feeder
feeder: feeders.feeder_ntu.Feeder_triple
train_feeder_args:
  data_path: /home/yxu/ctrgcn/CTR-GCN-main/data/ntu/NTU60_CS_8.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False

test_feeder_args:
  data_path: /home/yxu/ctrgcn/CTR-GCN-main/data/ntu/NTU60_CS_8.npz
  split: test
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: False
  debug: False

# model
model: model.ctrgcn.Model_moe
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
# weight_decay: 0.0004
# base_lr: 0.1
# lr_decay_rate: 0.1
# step: [10, 30]
# warm_up_epoch: 5
weight_decay: 0.0005
base_lr: 0.01
lr_decay_rate: 0.1
step: [10, 20]
warm_up_epoch: 1
# optimizer: Adam
# training
device: [0]
batch_size: 32
test_batch_size: 64
num_epoch: 10
nesterov: True
save_epoch: 0
save_score: True

#global sample selection
gss_forget_rate: 0.8